name: flutter_dashboard
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  equatable: ^2.0.5
  injectable: ^2.3.2
  flutter_bloc: ^8.1.3
#  simple_grid: ^0.1.4
  google_fonts: ^5.1.0
  intl: ^0.19.0
  fluttertoast: ^8.2.4
  collection: ^1.18.0
  syncfusion_flutter_datagrid: ^23.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner:
  flutter_gen_runner:
  injectable_generator:


flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/logo/
